### ISSUE TITLE
Add aarch64 support

### ISSUE THREAD

**Issue by berichta** [marthoc/hassio-addons#15] opened 2018-07-13 10:09 UTC
Within HassOS 1.5 (64bit) the current addon can't be installed. The system log states the following:

`18-07-13 10:06:32 ERROR (MainThread) [hassio.addons.addon] Addon 69bb46cb_deconz not supported on aarch64`

**Comment by marthoc** [comment] 2018-08-21 18:57
@lubbertkramer - I've taken a look at this but one dependency that deCONZ has (wiringpi) doesn't seem to have a 64-bit binary and I'm not crazy about compiling a 64-bit version inside the image. I'm going to keep looking into this.

**Comment by danielsjf** [comment] 2018-09-06 20:53
I have the same problem. It seems that that dependency is only needed for raspbee, not the conbee. Would it be possible as a temporal solution to have the addon only for the conbee?

**Comment by marthoc** [comment] 2018-09-06 20:55
This is possible. I’ll push a test version tonight.

**Comment by danielsjf** [comment] 2018-09-09 17:15
Let me know if I can help with testing anything :-)

**Comment by palmen** [comment] 2018-09-09 21:04
Would also greatly appreciate a 64-bit version.

**Comment by danielsjf** [comment] 2018-09-19 23:17
@marthoc Is there anything that I can do to help you with this?

**Comment by marthoc** [comment] 2018-09-26 16:51
@berichta @lubbertkramer @danielsjf @palmen I've just pushed version 2.05.39 of the add-on with experimental aarch64 support. Can you test if it's working on arch64 and report here? I don't have an RPi 3B+ to test for myself.

**Comment by nomadzx** [comment] 2018-09-28 15:43
@marthoc. I have installed the add-on on RPi 3B+. The installation went fine. I can confirm leaving a line in the config file was needed for me. I'm using discoverable and the deCONZ Zigbee gateway was discovered for my Raspbee. However, I cannot configure it yet as it cannot get the api key. I need to unlock in the Photoscon software to allow the retrieval of the API key (I'm guessing). It seems that I need to add a light to the Zigbee system, before I get any options in the Photoscon software. I went out last night to buy an Ikea TRÅDFRI light, as I am currently using Belkin Wemo lights with my SmartThings hub. I have attempted several times from the Photoscon software to find the TRÅDFRI light, but I am having problems with this as it is not seeing anything yet.

For completeness, here is the log from the add-on (I am using /dev/ttyAMA0):

`14:20:44:539 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
14:20:44:577 CTRL. 3.16.214:20:44:680 COM: --dev: /dev/ttyAMA0
14:20:44:727 dev /dev/ttyAMA0
14:20:44:727 COM: /dev/ttyAMA0 / serialno: 
14:20:44:727 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
14:20:45:155 parent process /bin/sh
14:20:45:155 gw run mode: normal
14:20:45:155 sd-card cid: 035344534336344780ffffffff0127e7
14:20:45:182 DB sqlite version 3.16.2
14:20:45:186 DB PRAGMA page_count: 30
14:20:45:186 DB PRAGMA page_size: 4096
14:20:45:187 DB PRAGMA freelist_count: 0
14:20:45:187 DB file size 122880 bytes, free pages 0
14:20:45:187 DB PRAGMA user_version: 6
14:20:45:187 DB cleanup
14:20:45:188 DB create temporary views
14:20:45:214 don't close database yet, keep open for 900 seconds
14:20:45:220 started websocket server at port 8443
14:20:45:229 discovery updated announce interval to 10 minutes
14:20:45:241 found node plugin: libde_rest_plugin.so - REST API Plugin
14:20:45:248 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
14:20:45:281 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
14:20:45:286 COM: --dev: /dev/ttyAMA0
14:20:45:327 dev /dev/ttyAMA0
14:20:45:327 COM: /dev/ttyAMA0 / serialno: 
14:20:45:394 discard sensor state push for 1: state/dark (already pushed)
14:20:45:531 discard sensor state push for 1: state/status (already pushed)
14:20:45:532 discard sensor state push for 1: state/lastupdated (already pushed)
14:20:45:681 New websocket 192.168.1.110:62080 (state: 3) 
14:20:45:858 device state timeout ignored in state 2
14:20:46:808 device state timeout ignored in state 2
14:20:47:783 device state timeout ignored in state 2
14:21:19:472 device state timeout ignored in state 2
14:21:20:472 device state timeout ignored in state 2
14:21:20:725 dev /dev/ttyAMA0
14:21:20:747 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x26240500.bin.GCF
14:21:20:969 Announced to internet
14:21:20:970 discovery server date: Fri, 28 Sep 2018 14:21:20 GMT
14:21:20:970 	 local time seems to be ok
14:21:20:970 discovery found version 2.04.35 for update channel stable
14:21:21:472 device state timeout (handled)
14:21:21:972 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
14:21:21:972 device state timeout ignored in state 4
14:21:48:184 scan skip host .140
14:21:53:877 scan finished
14:23:30:520 dev /dev/ttyAMA0
14:24:18:913 Content not completely loaded (got 0 of 0), wait 20ms
14:24:20:098 Content not completely loaded (got 0 of 0), wait 20ms
14:25:40:520 dev /dev/ttyAMA0
14:27:50:521 dev /dev/ttyAMA0
14:28:30:900 Websocket disconnected 192.168.1.110:62080 (state: 0) 
14:28:32:738 New websocket 192.168.1.110:62334 (state: 3) 
14:30:00:519 dev /dev/ttyAMA0
14:31:15:737 Announced to internet
14:31:15:737 discovery server date: Fri, 28 Sep 2018 14:31:15 GMT
14:31:15:737 	 local time seems to be ok
14:32:10:521 dev /dev/ttyAMA0
14:34:20:518 dev /dev/ttyAMA0
14:36:30:517 dev /dev/ttyAMA0
14:36:44:579 Content not completely loaded (got 0 of 0), wait 20ms
14:38:40:520 dev /dev/ttyAMA0
14:40:50:511 dev /dev/ttyAMA0
14:41:15:754 Announced to internet
14:41:15:754 discovery server date: Fri, 28 Sep 2018 14:41:15 GMT
14:41:15:754 	 local time seems to be ok
14:43:00:517 dev /dev/ttyAMA0
14:45:10:515 dev /dev/ttyAMA0
14:47:20:516 dev /dev/ttyAMA0
14:49:30:514 dev /dev/ttyAMA0
14:51:16:003 Announced to internet
14:51:16:004 discovery server date: Fri, 28 Sep 2018 14:51:15 GMT
14:51:16:004 	 local time seems to be ok
14:51:40:513 dev /dev/ttyAMA0
14:53:50:507 dev /dev/ttyAMA0
14:56:00:511 dev /dev/ttyAMA0
14:58:10:515 dev /dev/ttyAMA0
15:00:20:511 dev /dev/ttyAMA0
15:01:15:896 Announced to internet
15:01:15:896 discovery server date: Fri, 28 Sep 2018 15:01:15 GMT
15:01:15:897 	 local time seems to be ok
15:02:30:515 dev /dev/ttyAMA0
15:04:40:515 dev /dev/ttyAMA0
15:06:50:511 dev /dev/ttyAMA0
15:09:00:515 dev /dev/ttyAMA0
15:11:10:514 dev /dev/ttyAMA0
15:11:15:734 Announced to internet`

**Comment by marthoc** [comment] 2018-09-28 21:58
```
14:20:45:858 device state timeout ignored in state 2 14:20:46:808 device state timeout ignored in state 2 14:20:47:783 device state timeout ignored in state 2 14:21:19:472 device state timeout ignored in state 2 14:21:20:472 device state timeout ignored in state 2 
```
Tells me that deCONZ can’t find your device. Did you verify in Hassio system tab that /dev/ttyAMA0 exists?

**Comment by danielsjf** [comment] 2018-09-28 22:11
For me it works like a charm! Only some small issues with zigbee devices, but I don't think they are related to the 64 bit issue.

**Comment by danielsjf** [comment] 2018-09-28 22:13
Just for clarity, I managed to add the osram smart+ plug and an atari (lumi) door/window sensor.

**Comment by marthoc** [comment] 2018-10-02 18:04
Sounds like the aarch64 issue is resolved. Closing this. @nomadzx if you are still having your problem, please open a dedicated issue.

**Closed by marthoc** 2018-10-02 18:04 UTC
